FROM node:20-alpine3.20 AS build

WORKDIR /usr/src/app

COPY . .

RUN npm i && \
  npm run build

FROM nginx:alpine3.19-slim

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

COPY --from=build /usr/src/app/dist /usr/share/nginx/html

EXPOSE 8080
